from enum import Enum


class ReasonCode(str, Enum):
    ENOUGH_BUFFER = "ENOUGH_BUFFER"
    LOW_BUFFER_AFTER_PURCHASE = "LOW_BUFFER_AFTER_PURCHASE"
    PURCHASE_EXCEEDS_SAFE_TO_SPEND = "PURCHASE_EXCEEDS_SAFE_TO_SPEND"
    MANY_DAYS_UNTIL_SALARY = "MANY_DAYS_UNTIL_SALARY"
    EXPECTED_EXPENSES_HIGH = "EXPECTED_EXPENSES_HIGH"


