from enum import Enum


class ReasonCode(str, Enum):
    ENOUGH_BUFFER = "ENOUGH_BUFFER"
    LOW_BUFFER_AFTER_PURCHASE = "LOW_BUFFER_AFTER_PURCHASE"
    PURCHASE_EXCEEDS_SAFE_TO_SPEND = "PURCHASE_EXCEEDS_SAFE_TO_SPEND"
    MANY_DAYS_UNTIL_SALARY = "MANY_DAYS_UNTIL_SALARY"
    EXPECTED_EXPENSES_HIGH = "EXPECTED_EXPENSES_HIGH"
    SAFE_WEEKLY_SPEND_AVAILABLE = "SAFE_WEEKLY_SPEND_AVAILABLE"
    WEEKLY_SPEND_LIMITED_BY_PAYDAY_DISTANCE = (
        "WEEKLY_SPEND_LIMITED_BY_PAYDAY_DISTANCE"
    )
    NO_SAFE_WEEKLY_SPEND = "NO_SAFE_WEEKLY_SPEND"


